### ISSUE TITLE
When using Async Reports, Error incorrectly raised

### ISSUE THREAD

**Issue by maniac0059** [facebook/facebook-python-ads-sdk#177]
```
fields = [
    Insights.Field.account_name,
    Insights.Field.spend,
    Insights.Field.impressions,
    Insights.Field.actions,
    Insights.Field.video_p100_watched_actions,
    Campaign.Field.buying_type

]
aid = 'act_XXXXXXXXXXX'

i = AdAccount(aid).get_insights(fields=fields, async=True)
```

When running the above, these errors are returned:

`C:\Python27\lib\site-packages\facebookads-2.6.2-py2.7.egg\facebookads\utils\api_utils.py:30: UserWarning: insights does not allow field account_name
  warnings.warn(message)
C:\Python27\lib\site-packages\facebookads-2.6.2-py2.7.egg\facebookads\utils\api_utils.py:30: UserWarning: insights does not allow field spend
  warnings.warn(message)
C:\Python27\lib\site-packages\facebookads-2.6.2-py2.7.egg\facebookads\utils\api_utils.py:30: UserWarning: insights does not allow field impressions
  warnings.warn(message)
C:\Python27\lib\site-packages\facebookads-2.6.2-py2.7.egg\facebookads\utils\api_utils.py:30: UserWarning: insights does not allow field actions
  warnings.warn(message)
C:\Python27\lib\site-packages\facebookads-2.6.2-py2.7.egg\facebookads\utils\api_utils.py:30: UserWarning: insights does not allow field video_p100_watched_actions
  warnings.warn(message)
C:\Python27\lib\site-packages\facebookads-2.6.2-py2.7.egg\facebookads\utils\api_utils.py:30: UserWarning: insights does not allow field buying_type
  warnings.warn(message)`

However, the Async Job is successful.

**Comment by maniac0059** [comment]
cc @rituparnamukherjee

**Comment by rituparnamukherjee** [comment]
Hi @maniac0059 

Thanks for pointing this out. This is happening because we validate the allowed fields based on the return type of the api call. The discrepency in this case is due to the fact that the call is to insights endpoint but the return type is a AdReportRun Node.

You can ignore the errors for now since they are only warning. We will have this fixed in some time at our end.

**Comment by lfiaschi** [comment]
+1 one, is this there still ? I am using v2.8 and I still receive the same warnings ...

**Comment by lucascosta** [comment]
These can be ignored using:

```python
import warnings
warnings.simplefilter("ignore")
```

**Comment by Hiieu** [comment]
It's still not fixed, I don't understand why the ticket is closed.

**Comment by kavdev** [comment]
Can we get this reopened? It's coming up on two years since it wasn't fixed

**Comment by suhaasprasad** [comment]
+1

**Comment by luklss** [comment]
I have the same here, it would be nice if this warnings could be fixed.

**Comment by jdhau** [comment]
These warnings are still popping up. Not sure why this is closed!

**Comment by apurvis** [comment]
+1

**Comment by gitlech** [comment]
+1

**Comment by njindal** [comment]
+1

**Comment by lingchiachen** [comment]
+1

**Comment by adilkhash** [comment]
+1

**Comment by kingkiat** [comment]
+1

**Comment by adamszeptycki** [comment]
+1

**Comment by revmischa** [comment]
+1 lol

**Comment by codytwinton** [comment]
This has been resolved in `master`
